<?php

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findActive()
    {
        return $this
                ->createQueryBuilder('page')
                ->where('page.id > :id')
                    ->setParameter('id', 1)
                ->getQuery()
                ->getResult();


    }
}
